/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm.fbservices;

import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.Date;
import javafx.application.Platform;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javax.swing.JDialog;

/**
 *
 * @author Vinh
 */
public class LoginDialog extends javax.swing.JFrame {

    // tut
    // http://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm
    private JFXPanel _jfxPanel;
    private Scene _scene;

    private String _successUrl = "";
    private boolean _loggedin = false;

    public String _token;
    public Date _expiresDate;

    /**
     * Creates new form LoginDialog
     */
    public LoginDialog() {
        initComponents();
    }

    public LoginDialog(String name, String url, String redirect) {
        initComponents();
        
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        _successUrl = redirect;

        _jfxPanel = new JFXPanel();
        _jfxPanel.setBounds(0, 0, this.getWidth(), this.getHeight());
        this.add(_jfxPanel);

        Platform.runLater(() -> {
            Browser browser = new Browser(url);
            _scene = new Scene(browser, this.getWidth(), this.getHeight(), Color.web("#666970"));
            _jfxPanel.setScene(_scene);

            // process page loading
            browser.getWebEngine().getLoadWorker().stateProperty().addListener(
                    (ObservableValue<? extends Worker.State> ov, Worker.State oldState, Worker.State newState) -> {
                        if (newState == Worker.State.SUCCEEDED) {
                            String url1 = browser.getWebEngine().getLocation();
                            if (url1.contains(_successUrl) && _loggedin) {
                                extractURLInfo(url1);
                                // close frame and call event
                                LoginDialog.this.dispatchEvent(new WindowEvent(LoginDialog.this, WindowEvent.WINDOW_CLOSING));
                            }
                            _loggedin = true;
                        }
                    });

        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDialog().setVisible(true);
            }
        });
    }

    private void extractURLInfo(String url) {
        String fragments = url.substring(url.indexOf("#") + 1);
        String[] parameters = fragments.split("&");

        // Extract info from url
        for (String parameter : parameters) {
            String[] name_value = parameter.split("="); // Split the input

            switch (name_value[0]) {
                case "access_token":
                    _token = name_value[1];
                    break;
                case "expires_in":
                    Calendar cal = Calendar.getInstance();
                    cal.add(Calendar.SECOND, Integer.parseInt(name_value[1]));
                    _expiresDate = cal.getTime();
                    break;
                default:
                    break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
