/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.Album;
import facepalm.model.Photo;
import facepalm.model.User;
import facepalm.presenter.AlbumPresenterImpl;
import facepalm.presenter.IAlbumPresenter;
import facepalm.presenter.IPhotoPresenter;
import facepalm.presenter.PhotoPresenterImpl;


/**
 *
 * @author Stevie
 */
public class AlbumPanel extends javax.swing.JPanel implements IAlbumView {

    private IAlbumPresenter presenter;
    private IPhotoPresenter photoPresenter;
    
    /**
     * Creates new form AlbumPanel
     */
    public AlbumPanel() {
        initComponents();
        presenter = new AlbumPresenterImpl(this);
        photoPresenter = new PhotoPresenterImpl(new IPhotoView() {

            @Override
            public void startLoading(String componentId) {
                // do nothing.
            }

            @Override
            public void updateView(Photo photo) {
                Utils.loadImage(AlbumPanel.this.mImage, photo.getPicture());
//                EventQueue.invokeLater(new Runnable(){
//
//                    @Override
//                    public void run() {
//                    try {
//                            String path = photo.getPicture();
//                            URL url = new URL(path);
//                            BufferedImage image = ImageIO.read(url);
//                            AlbumPanel.this.mImage.setIcon(new ImageIcon(image));
//                        } catch (Exception exp) {
//                            exp.printStackTrace();
//                        }                        
//                    }
//                });
            }

            @Override
            public void updateListView(User.UserPhoto photos) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mAlbumName = new javax.swing.JLabel();
        mCount = new javax.swing.JLabel();
        mImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(200, 250));
        setMinimumSize(new java.awt.Dimension(200, 250));
        setPreferredSize(new java.awt.Dimension(200, 250));

        mAlbumName.setText("Album Name");

        mCount.setText("Photo Count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCount)
                            .addComponent(mAlbumName))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mAlbumName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mCount)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mAlbumName;
    private javax.swing.JLabel mCount;
    private javax.swing.JLabel mImage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void startLoading(String id) {
        presenter.loadAlbumInfo(id);
    }

    @Override
    public void updateView(Album album) {
        String coverId = album.getCoverPhoto().getId();
        photoPresenter.loadPhotoInfo(coverId);
        mCount.setText(String.valueOf(album.getCount()));
        mAlbumName.setText(album.getName());
        
    }
}
