/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.Comment;
import facepalm.model.User;
import facepalm.presenter.IPicturePresenter;
import facepalm.presenter.PicturePresenterImpl;

/**
 *
 * @author Stevie
 */
public class CommentView extends javax.swing.JPanel implements IPictureView{

    /**
     * Creates new form CommentView
     */
    public CommentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        _picture = new javax.swing.JLabel();
        _name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        _date = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0));
        _comment = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 56));
        jPanel2.setMinimumSize(new java.awt.Dimension(160, 56));

        _picture.setBackground(new java.awt.Color(204, 204, 204));
        _picture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        _picture.setMaximumSize(new java.awt.Dimension(56, 56));
        _picture.setMinimumSize(new java.awt.Dimension(56, 56));
        _picture.setPreferredSize(new java.awt.Dimension(56, 56));

        _name.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        _name.setForeground(new java.awt.Color(54, 88, 153));
        _name.setText("User Name");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        _date.setForeground(new java.awt.Color(144, 148, 156));
        _date.setText("time");
        jPanel1.add(_date);
        jPanel1.add(filler1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_name)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(jPanel2);

        _comment.setEditable(false);
        _comment.setColumns(20);
        _comment.setLineWrap(true);
        _comment.setRows(5);
        _comment.setText("...");
        _comment.setWrapStyleWord(true);
        _comment.setAlignmentX(0.0F);
        _comment.setBorder(null);
        _comment.setMaximumSize(new java.awt.Dimension(1000, 50));
        _comment.setMinimumSize(new java.awt.Dimension(160, 14));
        _comment.setPreferredSize(new java.awt.Dimension(164, 40));
        add(_comment);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea _comment;
    private javax.swing.JLabel _date;
    private javax.swing.JLabel _name;
    private javax.swing.JLabel _picture;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void setComment(Comment comment){
        _name.setText(comment.getFrom().getName());
        _comment.setText(comment.getMessage());
        
        if (comment.getCreatedTime()!= null)
            _date.setText(comment.getCreatedTime());
        else
            _date.setVisible(false);
        IPicturePresenter presenter = new PicturePresenterImpl(this);
        presenter.loadPeoplePicture(comment.getFrom().getId(), 100, 100);
    }

    @Override
    public void updateView(User.PictureWrap picture) {
        Utils.loadImage(_picture, picture.getUrl());
    }
}
