/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.Comment;
import facepalm.model.User;
import facepalm.presenter.IPicturePresenter;
import facepalm.presenter.PicturePresenterImpl;

/**
 *
 * @author Stevie
 */
public class CommentView extends javax.swing.JPanel implements IPictureView{

    /**
     * Creates new form CommentView
     */
    public CommentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _picture = new javax.swing.JLabel();
        _name = new javax.swing.JLabel();
        _comment = new javax.swing.JTextField();

        _picture.setText("jLabel1");
        _picture.setPreferredSize(new java.awt.Dimension(100, 100));

        _name.setText("name");

        _comment.setEditable(false);
        _comment.setBackground(new java.awt.Color(204, 204, 255));
        _comment.setText("jTextField1");
        _comment.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_name)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(_comment, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_comment)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _comment;
    private javax.swing.JLabel _name;
    private javax.swing.JLabel _picture;
    // End of variables declaration//GEN-END:variables

    public void setComment(Comment comment){
        _name.setText(comment.getFrom().getName());
        _comment.setText(comment.getMessage());
        IPicturePresenter presenter = new PicturePresenterImpl(this);
        presenter.loadPeoplePicture(comment.getFrom().getId(), 100, 100);
    }

    @Override
    public void updateView(User.PictureWrap picture) {
        Utils.loadImage(_picture, picture.getUrl());
    }
}
