/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import com.sun.media.jfxmedia.logging.Logger;
import facepalm.fbservices.Router;
import facepalm.fbservices.ServiceUtils;
import facepalm.model.User;
import facepalm.presenter.IUserPresenter;
import facepalm.presenter.UserPresenterImpl;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Group;
import javax.swing.JFrame;
import javax.swing.LayoutStyle;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author Stevie
 */
public class FacepalmForm extends javax.swing.JFrame implements IUserView{
    private static final String TAG =  FacepalmForm.class.getSimpleName();

    private static Router router = ServiceUtils.createService(Router.class);
    private static User mUser;

    private IUserPresenter  presenter;
    /**
     * Creates new form FacepalmForm
     */
    public FacepalmForm() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
                FacepalmForm.this.startView();
            }
            });
        presenter = new UserPresenterImpl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mAboutLabel = new javax.swing.JLabel();
        mBirthdayLabel = new javax.swing.JLabel();
        mEmailLabel = new javax.swing.JLabel();
        mGenderLabel = new javax.swing.JLabel();
        mQuoteLabel = new javax.swing.JLabel();
        mAboutText = new javax.swing.JLabel();
        mBirthdayText = new javax.swing.JLabel();
        mEmailText = new javax.swing.JLabel();
        mGenderText = new javax.swing.JLabel();
        mQuoteText = new javax.swing.JLabel();
        mPhotosPannel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setSize(new java.awt.Dimension(800, 700));

        mName.setText("Name");

        jPanel1.setMaximumSize(new java.awt.Dimension(251, 237));

        mAboutLabel.setLabelFor(mAboutText);
        mAboutLabel.setText("About");

        mBirthdayLabel.setText("Birthday");

        mEmailLabel.setText("Email");

        mGenderLabel.setText("Gender");

        mQuoteLabel.setText("Quote");

        mAboutText.setText("about");
        mAboutText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mAboutText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mAboutText.setMaximumSize(new java.awt.Dimension(130, 14));
        mAboutText.setMinimumSize(new java.awt.Dimension(130, 14));
        mAboutText.setPreferredSize(new java.awt.Dimension(130, 14));

        mBirthdayText.setText("birthday");

        mEmailText.setText("email");

        mGenderText.setText("gender");

        mQuoteText.setText("quote");
        mQuoteText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mQuoteText.setMaximumSize(new java.awt.Dimension(130, 14));
        mQuoteText.setMinimumSize(new java.awt.Dimension(130, 14));
        mQuoteText.setPreferredSize(new java.awt.Dimension(130, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mBirthdayLabel)
                            .addComponent(mEmailLabel)
                            .addComponent(mGenderLabel)
                            .addComponent(mQuoteLabel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mGenderText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mBirthdayText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mQuoteText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mAboutLabel)
                        .addGap(46, 46, 46)
                        .addComponent(mAboutText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mAboutLabel)
                    .addComponent(mAboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mBirthdayLabel)
                    .addComponent(mBirthdayText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmailLabel)
                    .addComponent(mEmailText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mGenderLabel)
                    .addComponent(mGenderText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mQuoteLabel)
                        .addGap(190, 190, 190))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mQuoteText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mPhotosPannel.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(mName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPhotosPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(mName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mPhotosPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FacepalmForm form = new FacepalmForm();
//                form.setVisible(true);
//            }
//        });
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mAboutLabel;
    private javax.swing.JLabel mAboutText;
    private javax.swing.JLabel mBirthdayLabel;
    private javax.swing.JLabel mBirthdayText;
    private javax.swing.JLabel mEmailLabel;
    private javax.swing.JLabel mEmailText;
    private javax.swing.JLabel mGenderLabel;
    private javax.swing.JLabel mGenderText;
    private javax.swing.JLabel mName;
    private javax.swing.JPanel mPhotosPannel;
    private javax.swing.JLabel mQuoteLabel;
    private javax.swing.JLabel mQuoteText;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void startView() {
        presenter.loadUserInfo();
    }

    @Override
    public void updateUserInfo(User user) {
        
        mName.setText(user.getName());
        mAboutText.setText(user.getAbout());
        mBirthdayText.setText(user.getBirthday());
        mEmailText.setText(user.getEmail());
        mGenderText.setText(user.getGender());
        mQuoteText.setText(user.getQuotes());
        
        
//        int albumCount = user.getAlbums().size();
//        GridLayout layout = (GridLayout)mPhotosPannel.getLayout();
//        layout.setRows(albumCount / 3);
//        layout.setColumns(3);
//        
//        for (int i = 0; i < albumCount; ++i) {
//            AlbumPanel panel = new AlbumPanel();
//            panel.startLoading(user.getAlbums().get(i).getId());
//            mPhotosPannel.add(user.getName(), panel);
//        }
//        mPhotosPannel.add(panel);
        
        
    }




}
