/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import com.sun.media.jfxmedia.logging.Logger;
import facepalm.fbservices.Router;
import facepalm.fbservices.ServiceUtils;
import facepalm.model.User;
import facepalm.presenter.IUserPresenter;
import facepalm.presenter.UserPresenterImpl;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import sun.rmi.runtime.Log;

/**
 *
 * @author Stevie
 */
public class FacepalmForm extends javax.swing.JFrame implements IUserView{
    private static final String TAG =  FacepalmForm.class.getSimpleName();

    private static Router router = ServiceUtils.createService(Router.class);
    private static User mUser;

    private IUserPresenter  presenter;
    /**
     * Creates new form FacepalmForm
     */
    public FacepalmForm() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
                FacepalmForm.this.startView();
            }
            });
        presenter = new UserPresenterImpl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mAboutLabel = new javax.swing.JLabel();
        mBirthdayLabel = new javax.swing.JLabel();
        mEmailLabel = new javax.swing.JLabel();
        mGenderLabel = new javax.swing.JLabel();
        mQuoteLabel = new javax.swing.JLabel();
        mAboutText = new javax.swing.JLabel();
        mBirthdayText = new javax.swing.JLabel();
        mEmailText = new javax.swing.JLabel();
        mGenderText = new javax.swing.JLabel();
        mQuoteText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));

        mAboutLabel.setText("About");

        mBirthdayLabel.setText("Birthday");

        mEmailLabel.setText("Email");

        mGenderLabel.setText("Gender");

        mQuoteLabel.setText("Quote");

        mAboutText.setText("about");

        mBirthdayText.setText("birthday");

        mEmailText.setText("email");

        mGenderText.setText("gender");

        mQuoteText.setText("quote");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mAboutLabel)
                        .addGap(46, 46, 46)
                        .addComponent(mAboutText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mBirthdayLabel)
                            .addComponent(mEmailLabel)
                            .addComponent(mGenderLabel)
                            .addComponent(mQuoteLabel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mQuoteText)
                            .addComponent(mGenderText)
                            .addComponent(mEmailText)
                            .addComponent(mBirthdayText))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAboutLabel)
                    .addComponent(mAboutText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mBirthdayLabel)
                    .addComponent(mBirthdayText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmailLabel)
                    .addComponent(mEmailText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mGenderLabel)
                    .addComponent(mGenderText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mQuoteLabel)
                    .addComponent(mQuoteText))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(mName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(mName)
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FacepalmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FacepalmForm form = new FacepalmForm();
//                form.setVisible(true);
//            }
//        });
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mAboutLabel;
    private javax.swing.JLabel mAboutText;
    private javax.swing.JLabel mBirthdayLabel;
    private javax.swing.JLabel mBirthdayText;
    private javax.swing.JLabel mEmailLabel;
    private javax.swing.JLabel mEmailText;
    private javax.swing.JLabel mGenderLabel;
    private javax.swing.JLabel mGenderText;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mQuoteLabel;
    private javax.swing.JLabel mQuoteText;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void startView() {
        presenter.loadUserInfo();
    }

    @Override
    public void updateUserInfo(User user) {
        mName.setText(user.getName());
        mAboutText.setText(user.getAbout());
        mBirthdayText.setText(user.getBirthday());
        mEmailText.setText(user.getEmail());
        mGenderText.setText(user.getGender());
        mQuoteText.setText(user.getQuotes());
        
    }




}
