/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.fbservices.Router;
import facepalm.fbservices.ServiceUtils;
import facepalm.model.Photo;
import facepalm.model.User;
import facepalm.presenter.IPhotoPresenter;
import facepalm.presenter.IPicturePresenter;
import facepalm.presenter.IUserPresenter;
import facepalm.presenter.PhotoPresenterImpl;
import facepalm.presenter.PicturePresenterImpl;
import facepalm.presenter.UserPresenterImpl;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

/**
 *
 * @author Stevie
 */
public class FbHomePage extends javax.swing.JFrame implements IUserView, IPictureView{
    private static final String TAG =  FbHomePage.class.getSimpleName();

    private static Router router = ServiceUtils.createService(Router.class);
    private static User mUser;

    private IUserPresenter  presenter;
    private IPicturePresenter picturePresenter;
    /**
     * Creates new form FbHomePage
     */
    public FbHomePage() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
                FbHomePage.this.startView();
            }
            });
        presenter = new UserPresenterImpl(this);
        picturePresenter = new PicturePresenterImpl(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _userName = new javax.swing.JLabel();
        _picture = new javax.swing.JLabel();
        _coverPhoto = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        leftPanel = new facepalm.LeftPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 766));
        setMinimumSize(new java.awt.Dimension(851, 766));
        setPreferredSize(new java.awt.Dimension(851, 766));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _userName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        _userName.setForeground(new java.awt.Color(255, 255, 255));
        _userName.setText("Name");
        _userName.setMaximumSize(new java.awt.Dimension(400, 22));
        getContentPane().add(_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        _picture.setBackground(new java.awt.Color(255, 255, 255));
        _picture.setText("Name");
        _picture.setToolTipText("");
        _picture.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        _picture.setIconTextGap(180);
        _picture.setMaximumSize(new java.awt.Dimension(180, 180));
        _picture.setMinimumSize(new java.awt.Dimension(180, 180));
        _picture.setName(""); // NOI18N
        _picture.setPreferredSize(new java.awt.Dimension(180, 180));
        getContentPane().add(_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        _coverPhoto.setBackground(new java.awt.Color(255, 255, 255));
        _coverPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _coverPhoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        _coverPhoto.setAlignmentX(Component.CENTER_ALIGNMENT);
        _coverPhoto.setMaximumSize(new java.awt.Dimension(851, 315));
        _coverPhoto.setMinimumSize(new java.awt.Dimension(851, 315));
        _coverPhoto.setPreferredSize(new java.awt.Dimension(851, 315));
        getContentPane().add(_coverPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane.setMaximumSize(new java.awt.Dimension(330, 370));
        jScrollPane.setMinimumSize(new java.awt.Dimension(330, 370));
        jScrollPane.setPreferredSize(new java.awt.Dimension(330, 370));
        jScrollPane.setViewportView(leftPanel);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 330, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FbHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FbHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FbHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FbHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FbHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _coverPhoto;
    private javax.swing.JLabel _picture;
    private javax.swing.JLabel _userName;
    private javax.swing.JScrollPane jScrollPane;
    private facepalm.LeftPanel leftPanel;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void startView() {
        presenter.loadUserInfo();
        picturePresenter.loadUserPicture(180, 180);
//        previewPhotoPanel.startLoading(null);
        leftPanel.loadPreviewPhoto();
    }

    @Override
    public void updateUserInfo(User user) {
        Utils.loadImage(_coverPhoto, user.getCover()._source);
        _userName.setText(user.getName());
//        profilePanel.getAboutLabel().setText(user.getAbout());
//        profilePanel.getBirthdayLabel().setText(user.getBirthday());
//        profilePanel.getGenderLabel().setText(user.getGender());
//        profilePanel.getQuoteLabel().setText(user.getQuotes());
//        profilePanel.getEmailLabel().setText(user.getEmail());
        leftPanel.setUserProfile(user);
    }

    @Override
    public void updateView(User.PictureWrap picture) {
        Utils.loadImage(_picture, picture.getUrl());
    }


}
