/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.BaseConnector;
import facepalm.model.User;
import facepalm.presenter.IPicturePresenter;
import facepalm.presenter.PicturePresenterImpl;
import javax.swing.JLabel;

/**
 *
 * @author Stevie
 */
public class Friend extends javax.swing.JPanel implements IPictureView{

    IPicturePresenter presenter;
    /**
     * Creates new form Frined
     */
    public Friend() {
        initComponents();
        presenter = new PicturePresenterImpl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _image = new javax.swing.JLabel();
        _name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(130, 150));
        setMinimumSize(new java.awt.Dimension(130, 150));
        setPreferredSize(new java.awt.Dimension(130, 150));

        _image.setText("jLabel1");
        _image.setMaximumSize(new java.awt.Dimension(130, 130));
        _image.setMinimumSize(new java.awt.Dimension(130, 130));
        _image.setPreferredSize(new java.awt.Dimension(130, 130));

        _name.setBackground(new java.awt.Color(255, 255, 255));
        _name.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        _name.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_name))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _image;
    private javax.swing.JLabel _name;
    // End of variables declaration//GEN-END:variables

    public void setFriend(BaseConnector f){
        _name.setText(f.getName());
        presenter.loadPeoplePicture(f.getId(), 130, 130);
    }

    @Override
    public void updateView(User.PictureWrap picture) {
        Utils.loadImage(_image, picture.getUrl());
    }
    
    public JLabel getNameLabel(){
        return _name;
    }
}
