/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.User;

/**
 *
 * @author Stevie
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePanel = new facepalm.ProfilePanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16));
        previewPhotoPanel = new facepalm.PreviewPhotoPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16));
        jLabel2 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16));
        preViewFriendPanel = new facepalm.PreViewFriendPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        setMaximumSize(new java.awt.Dimension(280, 32767));
        setMinimumSize(new java.awt.Dimension(280, 0));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        profilePanel.setAlignmentX(0.5F);
        add(profilePanel);
        add(filler3);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Photos:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jLabel1);
        add(filler1);
        add(previewPhotoPanel);
        add(filler2);

        jLabel2.setText("Friends:");
        add(jLabel2);
        add(filler4);
        add(preViewFriendPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private facepalm.PreViewFriendPanel preViewFriendPanel;
    private facepalm.PreviewPhotoPanel previewPhotoPanel;
    private facepalm.ProfilePanel profilePanel;
    // End of variables declaration//GEN-END:variables

    public void loadPreviewPhoto(){
        previewPhotoPanel.startLoading(null);
    }
    
    public void setUserProfile(User user){
        profilePanel.getAboutLabel().setText(user.getAbout());
        profilePanel.getBirthdayLabel().setText(user.getBirthday());
        profilePanel.getGenderLabel().setText(user.getGender());
        profilePanel.getQuoteLabel().setText(user.getQuotes());
        profilePanel.getEmailLabel().setText(user.getEmail());
        
        preViewFriendPanel.setUserFriend(user.getFriend());
    }
}
