/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.User.UserFriend;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Stevie
 */
public class PreViewFriendPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreViewFriendPanel
     */
    public PreViewFriendPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        setMaximumSize(new java.awt.Dimension(260, 32767));
        setMinimumSize(new java.awt.Dimension(260, 130));
        setPreferredSize(new java.awt.Dimension(260, 130));
        setLayout(new java.awt.GridLayout(1, 2, 4, 4));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void setUserFriend(UserFriend  friends){
        ((GridLayout) this.getLayout()).setRows(friends._photos.size() >> 1);
        this.setPreferredSize(new Dimension(260, 154 * ((friends._photos.size() - 1 )/ 2 + 1)));

        for (int i = 0; i < friends._photos.size(); i++) {
            Friend f = new Friend();
            f.setPreferredSize(new Dimension(130, 150));
            f.setMinimumSize(new Dimension(130, 150));
            f.setMaximumSize(new Dimension(130, 150));

            f.setFriend(friends._photos.get(i));
            this.add(f);
        }
    }

}
