/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facepalm;

import facepalm.model.User;
import javax.swing.JLabel;

/**
 *
 * @author Stevie
 */
public class ProfilePanel extends javax.swing.JPanel {

    private User _user;
    
    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _about = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        _birthday = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        _email = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        _gender = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _quote = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setAlignmentX(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(260, 320));
        setMinimumSize(new java.awt.Dimension(260, 320));
        setPreferredSize(new java.awt.Dimension(260, 320));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/globe.png"))); // NOI18N
        jLabel1.setText("Intro");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(new java.awt.Dimension(78, 50));

        _about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _about.setText("...");
        _about.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        _about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _about.setMaximumSize(new java.awt.Dimension(260, 24));
        _about.setMinimumSize(new java.awt.Dimension(260, 24));
        _about.setPreferredSize(new java.awt.Dimension(260, 24));

        jSeparator1.setMinimumSize(new java.awt.Dimension(330, 10));

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel3.setText("Birthday");

        _birthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _birthday.setText("...");
        _birthday.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        _birthday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _birthday.setMaximumSize(new java.awt.Dimension(260, 24));
        _birthday.setMinimumSize(new java.awt.Dimension(260, 24));
        _birthday.setPreferredSize(new java.awt.Dimension(260, 24));

        jSeparator2.setMinimumSize(new java.awt.Dimension(330, 10));

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel4.setText("Email");

        jSeparator3.setMinimumSize(new java.awt.Dimension(330, 10));

        _email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _email.setText("...");
        _email.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        _email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _email.setMaximumSize(new java.awt.Dimension(260, 24));
        _email.setMinimumSize(new java.awt.Dimension(260, 24));
        _email.setPreferredSize(new java.awt.Dimension(260, 24));

        jSeparator4.setMinimumSize(new java.awt.Dimension(330, 10));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel5.setText("Gender");

        _gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _gender.setText("...");
        _gender.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        _gender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _gender.setMaximumSize(new java.awt.Dimension(260, 24));
        _gender.setMinimumSize(new java.awt.Dimension(260, 24));
        _gender.setPreferredSize(new java.awt.Dimension(260, 24));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel6.setText("Quote");

        _quote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _quote.setText("...");
        _quote.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        _quote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _quote.setMaximumSize(new java.awt.Dimension(260, 24));
        _quote.setMinimumSize(new java.awt.Dimension(260, 24));
        _quote.setPreferredSize(new java.awt.Dimension(260, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_quote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(_birthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_about, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_quote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _about;
    private javax.swing.JLabel _birthday;
    private javax.swing.JLabel _email;
    private javax.swing.JLabel _gender;
    private javax.swing.JLabel _quote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

    public JLabel getBirthdayLabel(){
        return _birthday;
    }
    
    public JLabel getEmailLabel(){
        return _email;
    }
    
    public JLabel getGenderLabel(){
        return _gender;
    }
    
    public JLabel getQuoteLabel(){
        return _quote;
    }
    
    public JLabel getAboutLabel(){
        return _about;
    }

    /**
     * @return the _user
     */
    public User getUser() {
        return _user;
    }

    /**
     * @param user the _user to set
     */
    public void setUser(User user) {
        this._user = user;
    }
}
